### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by mschiegg** [reacherhq/check-if-email-exists#1149]
Socket hang up when i use Proxy.   
Without Proxy it works flawless

Error

```
[2022-05-05T08:04:27Z INFO  fast_socks5::client] Connected @ 51.15.199.33:11095
[2022-05-05T08:04:27Z DEBUG fast_socks5::client] Send version and method len [5, 1]
[2022-05-05T08:04:27Z DEBUG fast_socks5::client] client auth methods supported: [0]
[2022-05-05T08:04:27Z DEBUG fast_socks5::client] Socks version (5), method chosen: 2.
[2022-05-05T08:04:27Z INFO  fast_socks5::client] Password will be used
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fast-socks5-0.4.3/src/client.rs:183:42
```

But i don't have and i don't need any Password authentification   
Any Idea?

Full Log

```
[2022-05-05T08:04:27Z DEBUG hyper::proto::h1::io] parsed 7 headers 
[2022-05-05T08:04:27Z DEBUG hyper::proto::h1::conn] incoming body is content-length (144 bytes) 
[2022-05-05T08:04:27Z DEBUG hyper::proto::h1::conn] incoming body completed 
[2022-05-05T08:04:27Z DEBUG reacher] [email=****@****.ch] Checking with retry option Direct, attempt reacherhq/backend#2
[2022-05-05T08:04:27Z DEBUG check-if-email-exists] Checking email "****@****.ch"
[2022-05-05T08:04:27Z DEBUG check-if-email-exists] Found the following syntax validation: SyntaxDetails { address: Some(EmailAddress("****@****.ch")), domain: "****.ch", is_valid_syntax: true, username: "***.***" }
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::xfer::dns_handle] querying: ****.ch MX
[2022-05-05T08:04:27Z DEBUG trust_dns_resolver::name_server::name_server_pool] sending request: [Query { name: Name { is_fqdn: false, label_data: [108, 105, 110, 100, 101, 45, 107, 114, 121, 111, 116, 101, 99, 104, 110, 105, 107, 99, 104], label_ends: [17, 19] }, query_type: MX, query_class: IN }]
[2022-05-05T08:04:27Z DEBUG trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: 185.12.64.1:53, protocol: Udp, tls_dns_name: None, trust_nx_responses: false }
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::xfer] enqueueing message: [Query { name: Name { is_fqdn: false, label_data: [108, 105, 110, 100, 101, 45, 107, 114, 121, 111, 116, 101, 99, 104, 110, 105, 107, 99, 104], label_ends: [17, 19] }, query_type: MX, query_class: IN }]
[2022-05-05T08:04:27Z DEBUG trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: 185.12.64.2:53, protocol: Udp, tls_dns_name: None, trust_nx_responses: false }
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::xfer] enqueueing message: [Query { name: Name { is_fqdn: false, label_data: [108, 105, 110, 100, 101, 45, 107, 114, 121, 111, 116, 101, 99, 104, 110, 105, 107, 99, 104], label_ends: [17, 19] }, query_type: MX, query_class: IN }]
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::udp::udp_stream] created socket successfully
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::udp::udp_stream] created socket successfully
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::udp::udp_client_stream] received message id: 7288
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::xfer::dns_exchange] io_stream is done, shutting down
[2022-05-05T08:04:27Z DEBUG trust_dns_proto::xfer::dns_exchange] io_stream is done, shutting down
[2022-05-05T08:04:27Z DEBUG check-if-email-exists] Found the following MX hosts MxDetails { lookup: Ok(MxLookup(Lookup { query: Query { name: Name { is_fqdn: false, label_data: [108, 105, 110, 100, 101, 45, 107, 114, 121, 111, 116, 101, 99, 104, 110, 105, 107, 99, 104], label_ends: [17, 19] }, query_type: MX, query_class: IN }, records: [Record { name_labels: Name { is_fqdn: true, label_data: [108, 105, 110, 100, 101, 45, 107, 114, 121, 111, 116, 101, 99, 104, 110, 105, 107, 99, 104], label_ends: [17, 19] }, rr_type: MX, dns_class: IN, ttl: 3360, rdata: MX(MX { preference: 5, exchange: Name { is_fqdn: true, label_data: [76, 105, 110, 100, 101, 75, 114, 121, 111, 116, 101, 99, 104, 110, 105, 107, 45, 67, 72, 48, 49, 99, 109, 97, 105, 108, 112, 114, 111, 116, 101, 99, 116, 105, 111, 110, 111, 117, 116, 108, 111, 111, 107, 99, 111, 109], label_ends: [22, 26, 36, 43, 46] } }) }], valid_until: Instant { tv_sec: 152318, tv_nsec: 806626626 } })) }
[2022-05-05T08:04:27Z DEBUG check-if-email-exists] Found the following misc details: MiscDetails { is_disposable: false, is_role_account: false }
[2022-05-05T08:04:27Z DEBUG check-if-email-exists] Connecting to *******-CH01c.mail.protection.outlook.com.:25
[2022-05-05T08:04:27Z INFO  fast_socks5::client] Connected @ 51.15.199.33:11095
[2022-05-05T08:04:27Z DEBUG fast_socks5::client] Send version and method len [5, 1]
[2022-05-05T08:04:27Z DEBUG fast_socks5::client] client auth methods supported: [0]
[2022-05-05T08:04:27Z DEBUG fast_socks5::client] Socks version (5), method chosen: 2.
[2022-05-05T08:04:27Z INFO  fast_socks5::client] Password will be used
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fast-socks5-0.4.3/src/client.rs:183:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:69:5
   3: fast_socks5::client::Socks5Stream<async_std::net::tcp::stream::TcpStream>::connect_raw::{{closure}}
   4: check_if_email_exists::smtp::connect_to_host::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: check_if_email_exists::check_single_email::{{closure}}
   7: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
  11: <warp::filters::log::internal::WithLogFuture<FN,F> as core::future::future::Future>::poll
  12: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
  13: scoped_tls::ScopedKey<T>::set
  14: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  15: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
  16: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by amaurym** [comment]
Sorry for the silence. Are they errors still in the last v0.8.32 version? The fast-socks5 and async-smtp wiring has been updated in the latest versions.

**Comment by amaury1729** [comment]
Closed as stale
